const sampleCategories = [
  {
    name: "Notebooks",
    slug: "notebooks",
    description: "Archival Munken 120gsm paper with lay-flat Smyth sewn binding.",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop",
    displayOrder: 1,
  },
  {
    name: "Pens & Writing",
    slug: "pens-and-writing",
    description: "Solid brass, copper, and titanium writing tools machined to 0.01mm.",
    imageUrl: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=800&auto=format&fit=crop",
    displayOrder: 2,
  },
  {
    name: "Desk Accessories",
    slug: "desk-accessories",
    description: "Tuscan full-grain leather mats, stoneware pen rests, and brass weights.",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=800&auto=format&fit=crop",
    displayOrder: 3,
  },
  {
    name: "Fine Paper",
    slug: "fine-paper",
    description: "Hand-poured 100% recycled cotton sheets with natural deckled edges.",
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop",
    displayOrder: 4,
  },
  {
    name: "Art Supplies",
    slug: "art-supplies",
    description: "Acid-free cold-press watercolor blocks and pure botanical pigments.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop",
    displayOrder: 5,
  },
  {
    name: "Leather Goods",
    slug: "leather-goods",
    description: "Handcrafted vegetable-tanned journal covers and tool rolls.",
    imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop",
    displayOrder: 6,
  },
];

const sampleProducts = [
  {
    name: "Architect Hardcover Grid Journal",
    slug: "architect-hardcover-grid-journal",
    category: "Notebooks",
    description: "Engineered for designers and thinkers. 160 pages of 120gsm fountain pen friendly, ink-bleed resistant Swedish Munken paper with subtle 5mm dot grid.",
    indicativePrice: 1650,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: true,
    featured: true,
    stock: 45,
    specs: {
      paperGsm: "120 GSM Munken Lynx",
      binding: "Smyth Sewn Lay-Flat",
      color: "Charcoal Slate",
      dimensions: "148 x 210 mm (A5)",
      origin: "Stockholm, Sweden",
    },
  },
  {
    name: "Precision Machined Brass Fountain Pen",
    slug: "precision-machined-brass-fountain-pen",
    category: "Pens & Writing",
    description: "Solid raw brass construction CNC machined with 0.01mm tolerance. Fitted with a custom German iridium-tipped fine nib for effortless ink flow.",
    indicativePrice: 4800,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1585336261026-40742f3fa54e?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: true,
    featured: true,
    stock: 18,
    specs: {
      paperGsm: "N/A",
      binding: "Solid Brass & Iridium Nib",
      color: "Raw Machined Brass",
      dimensions: "135 mm length, 11 mm diameter",
      origin: "Munich, Germany",
    },
  },
  {
    name: "Minimalist Full-Grain Leather Desk Mat",
    slug: "minimalist-leather-desk-mat",
    category: "Desk Accessories",
    description: "Handcrafted from vegetable-tanned Tuscan leather. Features beveled burnished edges, non-slip natural wool felt backing, and magnetic cable organizer notch.",
    indicativePrice: 3450,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: true,
    featured: true,
    stock: 22,
    specs: {
      paperGsm: "N/A",
      binding: "Vegetable-tanned Leather & Felt",
      color: "Saddle Tan",
      dimensions: "800 x 400 x 3 mm",
      origin: "Florence, Italy",
    },
  },
  {
    name: "Cotton Rag Deckled Edge Letter Set",
    slug: "cotton-rag-deckled-edge-letter-set",
    category: "Fine Paper",
    description: "100% recycled cotton pulp handmade paper sheets with natural deckled edges. Includes 10 writing sheets and 10 wax-sealable matching envelopes.",
    indicativePrice: 1200,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: true,
    featured: false,
    stock: 35,
    specs: {
      paperGsm: "150 GSM Hand-poured Cotton",
      binding: "Hand Torn Deckle",
      color: "Warm Alabaster",
      dimensions: "A5 Sheets + C6 Envelopes",
      origin: "Kyoto, Japan",
    },
  },
  {
    name: "Matte Black Ceramic Pen Rest & Paperweight",
    slug: "matte-black-ceramic-pen-rest",
    category: "Desk Accessories",
    description: "Monolithic slip-cast stoneware with a tactile ultra-matte glaze. Sculpted channel cradles your favorite pen while keeping desk clutter to a minimum.",
    indicativePrice: 950,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: true,
    featured: false,
    stock: 14,
    specs: {
      paperGsm: "N/A",
      binding: "Stoneware Ceramic",
      color: "Matte Obsidian",
      dimensions: "90 x 35 x 20 mm",
      origin: "Copenhagen, Denmark",
    },
  },
  {
    name: "Botanical Pigment Watercolor Block",
    slug: "botanical-pigment-watercolor-block",
    category: "Art Supplies",
    description: "Cold-pressed 300gsm acid-free 100% cotton watercolor paper glued on all four sides to prevent buckling. Exceptional pigment absorption and blending.",
    indicativePrice: 2400,
    currency: "NRs.",
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=1000&auto=format&fit=crop",
    ],
    isAvailable: false,
    featured: false,
    stock: 0,
    specs: {
      paperGsm: "300 GSM Cold Press Cotton",
      binding: "4-Side Gummed Block",
      color: "Natural White",
      dimensions: "260 x 180 mm",
      origin: "Arches, France",
    },
  },
];

const sampleBanners = [
  {
    title: "Tactile Instruments for Deep Focus",
    subtitle: "Discover meticulously crafted notebooks, weighted brass instruments, and tactile desk essentials.",
    badge: "2026 Edition",
    imageUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=1800&auto=format&fit=crop",
    ctaText: "Explore Collection",
    ctaLink: "/products",
    alignment: "left",
    order: 1,
    isActive: true,
    accentColor: "#ffffff",
    overlayDarkness: 50,
  },
  {
    title: "Precision Machined Writing Instruments",
    subtitle: "Heavyweight brass and titanium pens engineered with micron tolerances for a lifetime of writing.",
    badge: "New Release",
    imageUrl: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=1800&auto=format&fit=crop",
    ctaText: "Discover Pens",
    ctaLink: "/products",
    alignment: "center",
    order: 2,
    isActive: true,
    accentColor: "#ffffff",
    overlayDarkness: 45,
  },
  {
    title: "Workspace Redefined: Natural Leather & Felt",
    subtitle: "Elevate your daily creative ritual with handcrafted desk pads and bespoke organizers.",
    badge: "Studio Highlight",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1800&auto=format&fit=crop",
    ctaText: "View Desk Essentials",
    ctaLink: "/products",
    alignment: "left",
    order: 3,
    isActive: true,
    accentColor: "#ffffff",
    overlayDarkness: 40,
  },
];

const sampleServices = [
  {
    title: "Starter Web Presence",
    slug: "starter-web-presence",
    category: "Web Development",
    shortDescription: "High-converting, ultra-fast landing page or up to 5-page modern web presence crafted for startups, professionals, and local businesses.",
    description: "Engineered with modern React and Tailwind CSS. Perfect for businesses and individuals seeking a high-converting, blazing-fast web presence. Includes clean responsive design across mobile/desktop, contact form with direct WhatsApp integration, on-page SEO optimization, and lightning-fast loading.",
    price: 25000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "5-7 Business Days",
    icon: "Globe",
    bannerImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Up to 5 Custom Responsive Pages / Landing Page",
      "Ultra-fast React + Vite Performance",
      "Mobile, Tablet & Desktop Pixel-Perfect Layouts",
      "Interactive Contact Form with Email & WhatsApp alerts",
      "Essential Technical SEO & Meta Tags setup",
      "Free Domain Mapping & SSL Certificate Setup",
      "1 Month Complimentary Post-Launch Support",
    ],
    technologies: ["React", "Tailwind CSS", "Vite", "SEO", "WhatsApp API"],
    isWebDevPackage: true,
    packageTier: "starter",
    tierBadge: "Essential",
    isFeatured: true,
    isActive: true,
    displayOrder: 1,
  },
  {
    title: "Professional Full-Stack Web App",
    slug: "professional-full-stack-web-app",
    category: "Web Development",
    shortDescription: "Comprehensive dynamic web application with bespoke Admin CMS, secure authentication, database persistence, and payment gateways.",
    description: "Our flagship web development solution. Designed for expanding companies, agencies, and digital brands that require real-time interactive dashboards, content management systems (CMS), custom database architecture, dynamic product/service catalogs, and seamless integration with Nepali payment gateways (eSewa / Khalti / Fonepay) and Stripe.",
    price: 55000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "2-3 Weeks",
    icon: "Code",
    bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Complete MERN / Next.js Full-Stack Architecture",
      "Custom Admin Studio Dashboard & CMS Control Panel",
      "User Authentication, JWT Security & Role Management",
      "Dynamic Database Schema (MongoDB / PostgreSQL)",
      "Nepali Payment Gateway Integration (eSewa, Khalti, Fonepay, Stripe)",
      "RESTful / GraphQL API Engine with Automated Validation",
      "Advanced On-Page & Schema Markup SEO",
      "Automated Transactional Emails & WhatsApp Notifier",
      "3 Months Priority Maintenance & SLA Guarantee",
    ],
    technologies: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "eSewa", "Khalti", "JWT"],
    isWebDevPackage: true,
    packageTier: "professional",
    tierBadge: "Most Popular / Recommended",
    isFeatured: true,
    isActive: true,
    displayOrder: 2,
  },
  {
    title: "Enterprise Platform & Scalable SaaS",
    slug: "enterprise-platform-scalable-saas",
    category: "Web Development",
    shortDescription: "Mission-critical custom enterprise software, complex multi-tenant SaaS, high-load e-commerce, and microservices.",
    description: "Architected for high concurrency, complex business workflows, and enterprise scale. Features multi-tenant SaaS architecture, cloud infrastructure containerization with Docker and Kubernetes, real-time WebSockets, microservices, advanced caching with Redis, automated CI/CD deployment pipelines, and stringent cybersecurity audits.",
    price: 120000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "4-6 Weeks",
    icon: "Layers",
    bannerImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Custom Enterprise Architecture / Multi-Tenant SaaS Engine",
      "High-Concurrency Microservices & Redis Caching Layer",
      "Real-time WebSocket Data Streams & Live Notifications",
      "Complex Business Workflow Automation & ERP/CRM Sync",
      "Automated CI/CD DevOps Pipeline (Docker, Kubernetes, AWS)",
      "Comprehensive OWASP Security Audit & Load Testing",
      "Multi-currency & Global Payment Processing",
      "Dedicated Senior Tech Lead & 6 Months Enterprise SLA",
    ],
    technologies: ["Next.js", "Node.js", "Docker", "AWS", "Redis", "PostgreSQL", "WebSockets", "CI/CD"],
    isWebDevPackage: true,
    packageTier: "enterprise",
    tierBadge: "Enterprise Scalable",
    isFeatured: true,
    isActive: true,
    displayOrder: 3,
  },
  {
    title: "Cross-Platform Mobile App Development",
    slug: "mobile-app-development",
    category: "Mobile Development",
    shortDescription: "High-performance native-feel iOS and Android mobile applications built with React Native and Flutter.",
    description: "We craft fluid, visually stunning mobile apps that offer native performance on both Apple iOS and Google Android. From intuitive UI interactions and camera/GPS hardware integrations to secure offline caching and push notifications.",
    price: 65000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "3-4 Weeks",
    icon: "Smartphone",
    bannerImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Cross-Platform iOS & Android Codebase (React Native / Flutter)",
      "Seamless Device Hardware Access (Biometrics, Camera, Location, Push)",
      "Offline SQLite/AsyncStorage Data Sync",
      "Apple App Store & Google Play Store Submission Management",
      "Smooth 60FPS Micro-animations & Gestures",
    ],
    technologies: ["React Native", "Flutter", "iOS", "Android", "Firebase", "Redux"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 4,
  },
  {
    title: "UI/UX & Interactive Design System",
    slug: "ui-ux-product-design",
    category: "UI/UX Design",
    shortDescription: "User-centered interface design, wireframing, high-fidelity Figma prototypes, and complete design systems.",
    description: "Transform complex workflows into elegant, intuitive digital experiences. Our design process includes user research, information architecture, clickable Figma prototypes, and comprehensive tokenized design systems ready for developer implementation.",
    price: 30000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "1-2 Weeks",
    icon: "Palette",
    bannerImage: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Comprehensive User Journey & Wireframe Mapping",
      "High-Fidelity Interactive Figma Prototypes",
      "Tokenized Design System with Dark/Light Variations",
      "Micro-interaction & Transition Specifications",
      "Seamless Developer Handoff with Asset Exports",
    ],
    technologies: ["Figma", "Design Tokens", "Wireframing", "Prototyping", "Design Systems"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 5,
  },
  {
    title: "Cloud Infrastructure & DevOps Automation",
    slug: "cloud-devops-solutions",
    category: "Cloud & DevOps",
    shortDescription: "Secure cloud migration, Docker containerization, Kubernetes orchestration, and automated CI/CD pipelines.",
    description: "Modernize your deployment workflow with bulletproof cloud infrastructure. We configure automated GitHub Actions pipelines, Docker containerization, Kubernetes clusters, load balancers, and cost-effective cloud architectures on AWS, DigitalOcean, and GCP.",
    price: 40000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "1-2 Weeks",
    icon: "Cloud",
    bannerImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Automated CI/CD Workflows via GitHub Actions / GitLab CI",
      "Docker Containerization & Kubernetes Cluster Setup",
      "AWS / DigitalOcean / GCP Server Optimization",
      "Automated Daily Backups, Failover & SSL Certificates",
      "Infrastructure as Code (Terraform) & Zero-Downtime Deploys",
    ],
    technologies: ["Docker", "Kubernetes", "AWS", "GitHub Actions", "Terraform", "Nginx", "Linux"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 6,
  },
  {
    title: "Cybersecurity Audit & Penetration Testing",
    slug: "cybersecurity-vulnerability-assessment",
    category: "Cybersecurity",
    shortDescription: "Comprehensive web & API penetration testing, OWASP Top 10 vulnerability assessment, and hardening.",
    description: "Safeguard your digital assets and customer data. We perform exhaustive penetration testing against web applications, REST APIs, and server infrastructure to identify zero-day vulnerabilities, SQL injection, XSS, and security misconfigurations before attackers do.",
    price: 45000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "1-2 Weeks",
    icon: "Shield",
    bannerImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop",
    features: [
      "OWASP Top 10 Web & API Vulnerability Scan",
      "Black-box & Gray-box Penetration Testing",
      "Authentication & Access Control Deep Audit",
      "SSL/TLS Hardening, Rate Limiting & DDoS Shield",
      "Executive Summary & Developer Actionable Remediation Report",
    ],
    technologies: ["OWASP", "Burp Suite", "SSL/TLS", "Penetration Testing", "Security Auditing"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 7,
  },
  {
    title: "AI Solutions & Custom Automation Engine",
    slug: "ai-solutions-custom-automation",
    category: "AI & Automation",
    shortDescription: "LLM AI chatbots, vector search embeddings, automated web scrapers, and third-party webhook integrations.",
    description: "Supercharge your business with custom Artificial Intelligence and workflow automation. We integrate OpenAI / Gemini LLM models with your proprietary knowledge base using vector databases, construct automated webhook data pipelines, and eliminate manual data entry.",
    price: 50000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "2-3 Weeks",
    icon: "Bot",
    bannerImage: "https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Custom AI Chatbots with RAG & Vector Embeddings",
      "Automated Data Extraction & Web Scraper Orchestration",
      "Third-Party CRM / ERP / POS Real-time Sync",
      "Zapier / Make / Webhook Workflow Automation",
      "Semantic Search & Intelligent Document Processing",
    ],
    technologies: ["OpenAI", "Gemini API", "Pinecone", "LangChain", "Python", "Node.js", "Webhooks"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 8,
  },
  {
    title: "Managed IT Support & Database Tuning",
    slug: "managed-it-support-database-tuning",
    category: "IT Consulting",
    shortDescription: "24/7 server health monitoring, database query optimization, index tuning, and technical advisory.",
    description: "Reliable engineering support for growing operations. We monitor your production servers 24/7, optimize sluggish database queries, configure clustering and replication, and provide direct technical consulting for strategic IT decisions.",
    price: 20000,
    priceType: "starting_at",
    currency: "NRs.",
    deliveryTime: "Ongoing Monthly / Retainer",
    icon: "Terminal",
    bannerImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
    features: [
      "24/7 Uptime & Server Resource Monitoring",
      "Database Query Optimization & Index Reconstruction",
      "Automated Disaster Recovery & Data Replication",
      "Monthly Security Patches & Dependency Updates",
      "Dedicated Slack / WhatsApp Escalation Channel",
    ],
    technologies: ["PostgreSQL", "MongoDB", "Redis", "Linux", "Grafana", "Prometheus"],
    isWebDevPackage: false,
    packageTier: "none",
    tierBadge: "",
    isFeatured: false,
    isActive: true,
    displayOrder: 9,
  },
];

const sampleServiceCategories = [
  {
    name: "Web Development",
    slug: "web-development",
    description: "Modern responsive web applications, full-stack MERN platforms, and custom SaaS architectures.",
    icon: "Globe",
    displayOrder: 1,
    isActive: true,
  },
  {
    name: "Mobile Development",
    slug: "mobile-development",
    description: "Cross-platform iOS and Android mobile applications built with React Native and Flutter.",
    icon: "Smartphone",
    displayOrder: 2,
    isActive: true,
  },
  {
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description: "User-centered design systems, Figma interactive prototypes, wireframes, and design tokens.",
    icon: "Palette",
    displayOrder: 3,
    isActive: true,
  },
  {
    name: "Cloud & DevOps",
    slug: "cloud-devops",
    description: "Cloud infrastructure automation, Docker containerization, Kubernetes, and CI/CD pipelines.",
    icon: "Cloud",
    displayOrder: 4,
    isActive: true,
  },
  {
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Vulnerability assessment, penetration testing, OWASP compliance, and security hardening.",
    icon: "Shield",
    displayOrder: 5,
    isActive: true,
  },
  {
    name: "AI & Automation",
    slug: "ai-automation",
    description: "Custom LLM integrations, RAG vector embeddings, automated scrapers, and webhook workflows.",
    icon: "Bot",
    displayOrder: 6,
    isActive: true,
  },
  {
    name: "IT Consulting",
    slug: "it-consulting",
    description: "24/7 server monitoring, database indexing & query optimization, and technical architecture advisory.",
    icon: "Terminal",
    displayOrder: 7,
    isActive: true,
  },
];

const samplePrintingServices = [
  {
    name: "Fine Art Giclée Archival Print",
    slug: "fine-art-giclee-archival-print",
    category: "Fine Art & Giclée",
    shortDescription: "Museum-grade pigment printing on 310 GSM 100% cotton rag with 100+ year archival color fidelity.",
    description: "Our signature giclée printing service produces gallery-ready reproductions with extraordinary tonal range and deep, velvety blacks. We utilize 12-color Lucia PRO archival pigment inks that resist fading for over a century. Ideal for photographers, fine artists, and limited edition art runs.",
    indicativePrice: 2800,
    discountPrice: 2450,
    costPrice: 1200,
    priceUnit: "per print (A3/A2)",
    currency: "NRs.",
    turnaroundTime: "24-48 Hours",
    stock: 250,
    isAvailable: true,
    featured: true,
    minOrderQuantity: 1,
    images: [
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["310 GSM Hahnemühle German Etching", "300 GSM Archival Velvet Cotton", "260 GSM Semi-Gloss Lustre"],
    finishOptions: ["Museum Matting", "Natural Deckled Edge", "Custom White Border"],
    supportedSizes: ["A4", "A3", "A3+", "A2", "A1", "Custom Panoramic"],
    specs: {
      paperGsm: "310 GSM 100% Cotton Rag",
      binding: "Archival Acid-Free Mount",
      color: "12-Color Lucia PRO Inks",
      dimensions: "Up to 44 inches width",
      printTechnology: "Wide-Format Fine Art Giclée",
      maxResolution: "2400 x 1200 DPI",
    },
    displayOrder: 1,
  },
  {
    name: "Architectural CAD & Engineering Blueprints",
    slug: "architectural-cad-engineering-blueprints",
    category: "Technical & CAD",
    shortDescription: "Crisp, ultra-precise CAD schematics, elevations, and structural drawings on high-contrast bond paper.",
    description: "Designed for architects, civil engineers, and construction contractors. We deliver sharp 0.1mm vector line fidelity, high-contrast monochrome and color plan prints, with automated folding or rolled delivery options.",
    indicativePrice: 450,
    discountPrice: 0,
    costPrice: 150,
    priceUnit: "per sheet (A1/A0)",
    currency: "NRs.",
    turnaroundTime: "Same Day (2-4 Hours)",
    stock: 500,
    isAvailable: true,
    featured: true,
    minOrderQuantity: 1,
    images: [
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["90 GSM Bright White Bond", "120 GSM Heavyweight Plan Paper", "80 GSM Translucent Vellum"],
    finishOptions: ["Standard Precision Folded", "Rolled with Plastic Sleeve", "Corner Stapled Binding"],
    supportedSizes: ["A2", "A1", "A0", "Custom Length Rolls"],
    specs: {
      paperGsm: "90-120 GSM High-Contrast Bond",
      binding: "Folded / Rolled / Strip Bound",
      color: "Monochrome & Full CAD Color",
      dimensions: "A2 (420x594mm) to A0 (841x1189mm)",
      printTechnology: "High-Speed Thermal Inkjet",
      maxResolution: "2400 x 1200 DPI",
    },
    displayOrder: 2,
  },
  {
    name: "Custom Foil Stamping & Hardcover Bookbinding",
    slug: "custom-foil-stamping-hardcover-bookbinding",
    category: "Document & Bookbinding",
    shortDescription: "Artisanal lay-flat hardcover binding with metallic gold/silver foil debossing on Dutch bookcloth.",
    description: "Transform your thesis, monograph, corporate report, or portfolio into a bespoke archival hardcover book. Crafted with precision Smyth sewn signatures, heavyweight endpapers, and heated brass die foil stamping.",
    indicativePrice: 3500,
    discountPrice: 3150,
    costPrice: 1600,
    priceUnit: "per volume",
    currency: "NRs.",
    turnaroundTime: "3-5 Business Days",
    stock: 120,
    isAvailable: true,
    featured: true,
    minOrderQuantity: 1,
    images: [
      "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["120 GSM Swedish Munken Book", "150 GSM Silk Coated", "100 GSM Natural Warm White"],
    finishOptions: ["Gold Metallic Foil", "Silver Holographic Foil", "Blind Deboss", "Black Matte Foil"],
    supportedSizes: ["A5", "A4", "US Letter", "Bespoke Square 210x210mm"],
    specs: {
      paperGsm: "120 GSM Munken + 3mm Bookboard",
      binding: "Smyth Sewn Hardcover + Ribbon Marker",
      color: "Full Color Offset & Digital",
      dimensions: "Custom Hardcover Dimensions",
      printTechnology: "Digital Offset + Heated Foil Die",
      maxResolution: "1200 x 1200 DPI",
    },
    displayOrder: 3,
  },
  {
    name: "Large Format Vinyl & Canvas Banners",
    slug: "large-format-vinyl-canvas-banners",
    category: "Large Format & Signage",
    shortDescription: "Weather-resistant 510 GSM flex vinyl and exhibition canvas prints with reinforced brass eyelets.",
    description: "Vibrant, heavy-duty signage and exhibition banners engineered for indoor and outdoor endurance. Printed with UV-resistant eco-solvent inks that withstand sun, rain, and repeated installation.",
    indicativePrice: 180,
    discountPrice: 150,
    costPrice: 70,
    priceUnit: "per sq. ft.",
    currency: "NRs.",
    turnaroundTime: "24 Hours",
    stock: 1000,
    isAvailable: true,
    featured: false,
    minOrderQuantity: 10,
    images: [
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["510 GSM Heavyweight Matte Vinyl", "440 GSM Gloss Flex", "380 GSM Stretched Cotton Canvas"],
    finishOptions: ["Reinforced Heat-Welded Hem", "Brass Eyelets every 2ft", "Pole Pockets Top/Bottom"],
    supportedSizes: ["Any custom width x length up to 10ft wide seamless"],
    specs: {
      paperGsm: "440 - 510 GSM Weatherproof Vinyl",
      binding: "Thermal Welded Hem + Grommets",
      color: "Eco-Solvent CMYK Extended Gamut",
      dimensions: "Custom Square Footage",
      printTechnology: "Wide-Format Eco-Solvent",
      maxResolution: "1440 DPI",
    },
    displayOrder: 4,
  },
  {
    name: "Luxury Letterpress & Embossed Business Cards",
    slug: "luxury-letterpress-embossed-business-cards",
    category: "Commercial & Corporate",
    shortDescription: "Ultra-thick 600 GSM double-pasted cotton paper with deep tactile letterpress relief impression.",
    description: "Make an unforgettable tactile impression. Printed on heavy 600 GSM cotton stock using authentic vintage letterpress machinery with deep impression depth and hand-painted metallic edge gilding.",
    indicativePrice: 4200,
    discountPrice: 3800,
    costPrice: 1800,
    priceUnit: "per 100 cards",
    currency: "NRs.",
    turnaroundTime: "2-3 Business Days",
    stock: 200,
    isAvailable: true,
    featured: true,
    minOrderQuantity: 100,
    images: [
      "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["600 GSM Crane's Lettra 100% Cotton", "540 GSM Colorplan Pure Extra White", "700 GSM Triplex Sandwich"],
    finishOptions: ["Deep Letterpress Impression", "Gold Edge Gilding", "Blind Debossing", "Pantone Spot Inks"],
    supportedSizes: ["90 x 50 mm (Standard)", "85 x 55 mm (European)", "Square 65 x 65 mm"],
    specs: {
      paperGsm: "600 GSM Cotton Double-Pasted",
      binding: "Precision Guillotine Cut",
      color: "Pantone Matching System (PMS)",
      dimensions: "90 x 50 mm Standard",
      printTechnology: "Vintage Heidelberg Letterpress",
      maxResolution: "Cast Iron Mechanical Relief",
    },
    displayOrder: 5,
  },
  {
    name: "Custom Matte & Gloss Product Packaging",
    slug: "custom-matte-gloss-product-packaging",
    category: "Packaging & Labels",
    shortDescription: "Die-cut folding cartons, sleeve packaging, and waterproof product labels with spot UV gloss.",
    description: "Elevate your retail merchandise with custom-engineered folding boxes, rigid boxes, and waterproof bottle/cosmetic labels. Features soft-touch velvet lamination and high-gloss spot UV accents.",
    indicativePrice: 65,
    discountPrice: 0,
    costPrice: 28,
    priceUnit: "per box (Min. 50 pcs)",
    currency: "NRs.",
    turnaroundTime: "4-7 Business Days",
    stock: 500,
    isAvailable: true,
    featured: false,
    minOrderQuantity: 50,
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
    ],
    paperOptions: ["350 GSM SBS Bleached Folding Board", "400 GSM Unbleached Kraft Board", "Waterproof Vinyl Decal Paper"],
    finishOptions: ["Soft-Touch Velvet Matte", "Spot UV High Gloss", "Custom Die-Cut Window", "Foil Highlights"],
    supportedSizes: ["Custom 3D CAD Folding Templates"],
    specs: {
      paperGsm: "350 - 400 GSM Solid Bleached Sulfate",
      binding: "Die-cut Creased & Glued Box",
      color: "Full Color Process + Spot Colors",
      dimensions: "Bespoke Packaging Dimensions",
      printTechnology: "Industrial Digital Packaging Press",
      maxResolution: "2400 x 2400 DPI",
    },
    displayOrder: 6,
  },
];

const defaultShopStatus = {
  isOpen: true,
  title: "Pixel Perfect is Open",
  partialTitle: "Partial Service Availability • Selected Hours",
  closedMessage:
    "We are currently closed for off-hours / maintenance. You can still explore our catalog and submit project inquiries or WhatsApp messages. We will process them immediately once open!",
  partialMessage:
    "Some particular services are currently undergoing maintenance or unavailable, while our core stationery catalog and select digital services remain actively operational with their scheduled timings.",
  openMessage: "We are currently open and taking orders and consulting inquiries.",
  bannerNotice: "",
  timerEnabled: false,
  timerTarget: null,
  timerLabel: "Next Window In",
  timerAction: "reopen",
  showPopupWhenClosed: true,
  contactPhone: "+977 9845991878",
  contactEmail: "perfectpixel300@gmail.com",
};

const samplePromoBanners = [
  {
    badge: "Our Philosophy",
    title: '"Quality materials, thoughtful design, and tools built to last."',
    subtitle:
      "Pixel Perfect designs and delivers premium stationery, solid writing instruments, leather desk accessories, and modern digital services.",
    imageUrl: "",
    hasTimer: false,
    timerEndDate: null,
    timerTitle: "Offer Ends In",
    ctaText: "Explore Collection",
    ctaLink: "/products",
    alignment: "center",
    style: "philosophy",
    order: 1,
    isActive: true,
  },
];

module.exports = {
  sampleCategories,
  sampleProducts,
  sampleBanners,
  samplePromoBanners,
  sampleServices,
  sampleServiceCategories,
  samplePrintingServices,
  defaultShopStatus,
};


